let a = "string";
let b = 1;
let c = false;
let d = null;
let e;
let f = {};

console.log(a / a);
console.log(a / b);
console.log(a / c);
console.log(a / d);
console.log(a / e);
console.log(a / f);
console.log(b / a);
console.log(b / b);
console.log(b / c);
console.log(b / d);
console.log(b / e);
console.log(b / f);
console.log(c / a);
console.log(c / b);
console.log(c / c);
console.log(c / d);
console.log(c / e);
console.log(c / f);
console.log(d / a);
console.log(d / b);
console.log(d / c);
console.log(d / d);
console.log(d / e);
console.log(d / f);
console.log(e / a);
console.log(e / b);
console.log(e / c);
console.log(e / d);
console.log(e / e);
console.log(e / f);
console.log(f / a);
console.log(f / b);
console.log(f / c);
console.log(f / d);
console.log(f / e);
console.log(f / f);